version: '3.7'
services:
  redis:
    image: redis:6.2.2-alpine
    container_name: rd01
    env_file:
      - ./.env.dev
    ports:
      - '6379:6379'
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    environment:
      makemigrations: "python manage.py makemigrations"
      migrate: "python manage.py migrate"
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=FakeCSV
  celery:
    build: .
    command: celery -A ToDo worker -B -l info -f celery.logs
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - db
      - redis

volumes:
  postgres_data: