# Generated by Django 3.1 on 2021-05-08 15:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='PeriodOfTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 15, 23, 23, 439759, tzinfo=utc)),
        ),
    ]
